name: RandomTPCC
main: net.clownercraft.randomtpCC.RandomTPCC
version: 1.3.2
api-version: 1.16
commands:
  randomtp:
    aliases: [rtp, randtp]
    description: Teleport to a random location
    usage: /rtp [world]